### ISSUE TITLE
tcp connections to https

### ISSUE THREAD

**Issue by MSP-Greg** [MSP-Greg/puma#2]
@nateberkopec

Thought I'd ping you from here re the issue with a TCP connections coming into a Puma SSL server, which is an issue particular to TLSv1.3.

While reviewing the OpenSSL man pages, I even came across a somewhat cryptic note (that I now can't find, as I didn't bookmark it) that alluded to this issue.  It wasn't TCP specific, but it mentioned that TLSv1.3 doesn't close connections that don't properly start a handshake, unlike older protocol versions.  It was framed from the standpoint of 'if you're monitoring several clients, you might want to...'

Anyway, I've got a branch here that seems to fix the issue. Before I implemented it, client TCP connections weren't closed, they timed out.  Now they close rather quickly.  I choose to do it based on the number of reads done in `engine_read_all`, but it could be time based.

Also, it seems to remove error messages like 'Error in reactor loop escaped':
https://travis-ci.org/puma/puma/jobs/566635594#L1670
with the update (ignore the output, that's me testing):
https://travis-ci.org/MSP-Greg/puma/jobs/567195930#L1849

JFYI, I was working with beta versions of OpenSSL 1.1.1, and testing with Ruby, Puma, and EventMachine.

EM makes use of SSL callbacks, and I recalled that things needed updates in EM, as several of the tests assumed an order for callbacks in terms of the client and the server.  Because of the callbacks, it's up to the 'user' to check for status, which sometime soon I'll bring up there.

Puma doesn't have the callbacks, so we need the logic, which in some respects is better, as the user can't screw it up.

I guess all that old stuff bouncing around led to the question of 'does Puma drop TCP connections?'

Anyway, part of the reason I pinged you is that this branch is built on top of PR 1857, and it may have merge issues with two of my PR's.  I also need to add a bit more to optimize it.

Just thought I'd update you...

**Comment by nateberkopec** [comment]
Which branch on _this_ repo are you working on?

**Comment by MSP-Greg** [comment]
Sorry.  It's in the Travis log, anyway [ssl-vers](https://github.com/MSP-Greg/puma/tree/ssl-vers).

Also, part of the reason I brought it up here is I'd like to keep the issue of 'tcp connections mess up Puma with TLSvv1.3' a little less public...

**Comment by nateberkopec** [comment]
🤷‍♂ The protocol has only been published for a year, not a surprise that we're not supporting it very well.

**Comment by MSP-Greg** [comment]
I wasn't being negative or anything.  I think a lot of devs never stop to think about how complex an app like Puma is, and they often act as if there's infinite resources behind it.  Common with OSS.

Regardless, I think there's a good group of people involved, and we can fix a lot of the issues.

JFYI, I'm trying to comment things a lot better.

**Comment by nateberkopec** [comment]
Oh sure! I'm just saying I don't see the need for secrecy. If no one knows that TCP and TLSv1.3 don't work well with Puma, we can't fix it.
